process-info.browse=Processing Info
process-info.columns.id=ID
process-info.columns.name=Name
process-info.columns.url=URL
process-info.create=Create Processing Info
process-info.create.actions.submit=Create
process-info.update=Update Processing Info
process-info.update.actions.submit=Save
process-info.update.actions.delete=Delete
process-info.fields.id=ID
process-info.fields.name=Name
process-info.fields.url=URL